/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { UserPortfolio } from "./UserPortfolio";
import { UserPortfolioCountArgs } from "./UserPortfolioCountArgs";
import { UserPortfolioFindManyArgs } from "./UserPortfolioFindManyArgs";
import { UserPortfolioFindUniqueArgs } from "./UserPortfolioFindUniqueArgs";
import { DeleteUserPortfolioArgs } from "./DeleteUserPortfolioArgs";
import { UserPortfolioService } from "../userPortfolio.service";
@graphql.Resolver(() => UserPortfolio)
export class UserPortfolioResolverBase {
  constructor(protected readonly service: UserPortfolioService) {}

  async _userPortfoliosMeta(
    @graphql.Args() args: UserPortfolioCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [UserPortfolio])
  async userPortfolios(
    @graphql.Args() args: UserPortfolioFindManyArgs
  ): Promise<UserPortfolio[]> {
    return this.service.userPortfolios(args);
  }

  @graphql.Query(() => UserPortfolio, { nullable: true })
  async userPortfolio(
    @graphql.Args() args: UserPortfolioFindUniqueArgs
  ): Promise<UserPortfolio | null> {
    const result = await this.service.userPortfolio(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserPortfolio)
  async deleteUserPortfolio(
    @graphql.Args() args: DeleteUserPortfolioArgs
  ): Promise<UserPortfolio | null> {
    try {
      return await this.service.deleteUserPortfolio(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
