/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CryptoAsset } from "./CryptoAsset";
import { CryptoAssetCountArgs } from "./CryptoAssetCountArgs";
import { CryptoAssetFindManyArgs } from "./CryptoAssetFindManyArgs";
import { CryptoAssetFindUniqueArgs } from "./CryptoAssetFindUniqueArgs";
import { DeleteCryptoAssetArgs } from "./DeleteCryptoAssetArgs";
import { CryptoAssetService } from "../cryptoAsset.service";
@graphql.Resolver(() => CryptoAsset)
export class CryptoAssetResolverBase {
  constructor(protected readonly service: CryptoAssetService) {}

  async _cryptoAssetsMeta(
    @graphql.Args() args: CryptoAssetCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CryptoAsset])
  async cryptoAssets(
    @graphql.Args() args: CryptoAssetFindManyArgs
  ): Promise<CryptoAsset[]> {
    return this.service.cryptoAssets(args);
  }

  @graphql.Query(() => CryptoAsset, { nullable: true })
  async cryptoAsset(
    @graphql.Args() args: CryptoAssetFindUniqueArgs
  ): Promise<CryptoAsset | null> {
    const result = await this.service.cryptoAsset(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CryptoAsset)
  async deleteCryptoAsset(
    @graphql.Args() args: DeleteCryptoAssetArgs
  ): Promise<CryptoAsset | null> {
    try {
      return await this.service.deleteCryptoAsset(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
